###

GET https://poke-api-hono.diegoaporterol.workers.dev/api/user

###

GET https://poke-api-hono.diegoaporterol.workers.dev/api/user/top
###

GET https://poke-api-hono.diegoaporterol.workers.dev/api/user/1

###

POST https://poke-api-hono.diegoaporterol.workers.dev/api/user
Content-type: application/json

{
    "name": "Oso9",
    "score": 90
}

###

PUT https://poke-api-hono.diegoaporterol.workers.dev/api/user/2
Content-type:  application/json

{
    "name": "John Doe",
    "score": 70
}

###

DELETE https://poke-api-hono.diegoaporterol.workers.dev/api/user/2